# Builds WowLabs and packages it into a folder you can hand to someone.
#
#   .\tools\package.ps1
#   .\tools\package.ps1 -SkipBuild        # package what is already in dist\
#
# The result is build\WowLabs\WowLabs.exe, which runs with nothing installed:
# no LuaJIT on the machine, no Lua path to set, no working directory to be in.
# That is the thing to test each addition against, because it is the thing
# anybody else will run.
#
# The packaging itself is Neutrino's - this only says what belongs in it.

param(
    # Package what dist\ already holds instead of building first.
    [switch]$SkipBuild,

    # Where to put the result. Defaults to build\WowLabs.
    [string]$OutDir = "",

    # Open the folder when it is done.
    [switch]$Show,

    # Skip starting the packaged application to see that it comes up.
    [switch]$SkipSmoke
)

$ErrorActionPreference = "Stop"

$RootDir = Resolve-Path (Join-Path $PSScriptRoot "..")
$DistDir = Join-Path $RootDir "dist"
$Neutrino = Join-Path $RootDir "vendor\neutrino"

if (-not $OutDir) { $OutDir = Join-Path $RootDir "build\WowLabs" }

# --- Build ------------------------------------------------------------------
#
# Always, unless told otherwise. A package built from a stale dist\ is the kind
# of thing that is only noticed after it has been sent to someone.

if (-not $SkipBuild) {
    & (Join-Path $RootDir "tools\build.ps1")
    if ($LASTEXITCODE -ne 0) { throw "Build failed." }
    Write-Host ""
}

$StaticDist = Join-Path $DistDir "static"
if (-not (Test-Path (Join-Path $StaticDist "app.css"))) {
    Write-Host "dist\static\app.css is missing. Build first." -ForegroundColor Red
    exit 1
}

# The 3.3.5 definitions, generated by the build from the submodule's 193 MB of
# every build there has ever been. Without them the editor lists the client's
# tables and refuses to open any of them.
$DefsDist = Join-Path $DistDir "definitions"
if (-not (Test-Path (Join-Path $DefsDist "Spell.json"))) {
    Write-Host "dist\definitions is missing or empty. Build first." -ForegroundColor Red
    exit 1
}

# --- Package ----------------------------------------------------------------
#
# The compiled stylesheet comes from dist\ rather than from static\, because it
# is generated at build time and static\ holds the source it is generated from.

& (Join-Path $Neutrino "tools\package.ps1") `
    -Name "WowLabs" `
    -Entry (Join-Path $RootDir "src\main.moon") `
    -AppSrc @(
        (Join-Path $RootDir "src"),
        (Join-Path $RootDir "vendor\lua-dbc\src")
    ) `
    -Include @($StaticDist, $DefsDist) `
    -OutDir $OutDir

if ($LASTEXITCODE -ne 0) { throw "Packaging failed." }

# --- Check it is whole ------------------------------------------------------
#
# Named files rather than a size: a package that is missing one of these starts
# and then fails in a message box, which is the worst way to find out.

$required = @(
    "WowLabs.exe",
    "lua51.dll",
    "app\main.lua",
    "app\neutrino.lua",
    "app\shell\window.lua",
    "app\shell\settings.lua",
    "app\settings.lua",
    "app\workspace.lua",
    "app\modules\dbc\init.lua",
    "app\modules\dbc\editor.lua",
    "app\modules\dbc\changes.lua",
    "app\modules\dbc\relations.lua",
    "app\modules\dbc\query.lua",
    "app\dbc\init.lua",

    # The markup and the scripts. moonc walks past these, so they arrive by a
    # different route than the code that reads them, and a route that is not
    # taken is a route nothing notices until the application will not start.
    "app\shell\views\shell.etlua",
    "app\shell\views\settings.etlua",
    "app\shell\views\tool-card.etlua",
    "app\modules\dbc\views\grid.etlua",
    "app\modules\dbc\scripts\grid.js",

    "rocks\lib\lua\5.1\cjson.dll",
    "definitions\Spell.json",
    "definitions\ItemBagFamily.json",
    "static\app.css",
    "bin\neutrinocef.dll",
    "bin\neutrinocef_helper.exe"
)

$missing = @()
foreach ($item in $required) {
    if (-not (Test-Path (Join-Path $OutDir $item))) { $missing += $item }
}

if ($missing.Count -gt 0) {
    Write-Host ""
    Write-Host "The package is incomplete:" -ForegroundColor Red
    foreach ($item in $missing) { Write-Host "  missing $item" -ForegroundColor Red }
    exit 1
}

# --- Check it runs ----------------------------------------------------------
#
# Complete is not the same as working. A file resolved against the wrong root,
# a module that raises while registering itself - either one leaves every named
# file present and the application dead before its window appears, with two
# lines in a log and nothing on screen. That happened, and the check above said
# the package was fine.
#
# So it is started, once, and asked to say it got to the shell. Under its own
# LOCALAPPDATA, so this neither writes into the log somebody is reading nor
# fights an instance they already have open.
#
# Reaching the shell is not enough on its own. The page is served over the
# scheme handler, and the router turns a template that raises into a warning
# and an error page - so the window comes up, "shell ready" is logged, and the
# application is blank. A clean start logs two INFO lines and nothing else, so
# anything louder than that is the failure.

if (-not $SkipSmoke) {
    Write-Host ""
    Write-Host "[wowlabs] Starting it once..." -ForegroundColor Cyan

    $sandbox = Join-Path ([System.IO.Path]::GetTempPath()) "wowlabs-smoke-$PID"
    if (Test-Path $sandbox) { Remove-Item -Recurse -Force $sandbox }
    New-Item -ItemType Directory -Path $sandbox -Force | Out-Null

    $log = Join-Path $sandbox "WowLabs\WowLabs.log"
    $restore = $env:LOCALAPPDATA
    $env:LOCALAPPDATA = $sandbox

    try {
        $app = Start-Process -FilePath (Join-Path $OutDir "WowLabs.exe") -PassThru
    } finally {
        $env:LOCALAPPDATA = $restore
    }

    $ready = $false
    for ($i = 0; $i -lt 60; $i++) {
        Start-Sleep -Milliseconds 500
        if ((Test-Path $log) -and ((Get-Content $log -Raw) -match "shell ready")) {
            $ready = $true
            break
        }
        if ($app.HasExited) { break }
    }

    if (-not $app.HasExited) { Stop-Process -Id $app.Id -Force }
    Start-Sleep -Milliseconds 1000

    # Its helpers are its children; one left behind holds the cache directory
    # and the next run dies four seconds in saying nothing.
    Get-Process -Name "neutrinocef_helper" -ErrorAction SilentlyContinue |
        Where-Object { $_.Path -and $_.Path.StartsWith($OutDir) } |
        Stop-Process -Force -ErrorAction SilentlyContinue

    $complained = @()
    if (Test-Path $log) {
        $complained = @(Get-Content $log | Where-Object { $_ -match "WARN|ERROR" })
    }

    if ((-not $ready) -or $complained.Count -gt 0) {
        Write-Host ""
        if (-not $ready) {
            Write-Host "It started and never reached the shell." -ForegroundColor Red
        } else {
            Write-Host "It came up, but it was not happy about it." -ForegroundColor Red
        }

        if (Test-Path $log) {
            Get-Content $log -Tail 25 |
                ForEach-Object { Write-Host "  $_" -ForegroundColor DarkGray }
        } else {
            Write-Host "  nothing was logged at $log" -ForegroundColor DarkGray
        }
        exit 1
    }

    Remove-Item -Recurse -Force $sandbox -ErrorAction SilentlyContinue
    Write-Host "          it reached the shell, quietly." -ForegroundColor Green
}

$size = (Get-ChildItem -Path $OutDir -Recurse -File |
    Measure-Object -Property Length -Sum).Sum

Write-Host ""
Write-Host "[wowlabs] Packaged to $OutDir ($([math]::Round($size / 1mb)) MB)" -ForegroundColor Green
Write-Host "          Run it with `"$OutDir\WowLabs.exe`"" -ForegroundColor Green

if ($Show) { Start-Process explorer.exe $OutDir }
